### ISSUE TITLE
Model a "Create a wishlist" business process

### ISSUE THREAD

**Issue by minndoo** [minndoo/varwish-modelling#1]

**Comment by tonyskansf** [comment]
**Creating wishlist**
- Creating wishlist is one of primary processes in the app that creates an empty wishlist and allows the user to maintain (add, edit, etc.) items within the wishlist.

- _Adding item_
Adding an item is a sub-process while creating a wishlist. This process is described in detail in the following chapter.

Opravte pripadne okomentujte co byste zmenili.
