### ISSUE TITLE
Model a "Adding items" business process

### ISSUE THREAD

**Issue by minndoo** [minndoo/varwish-modelling#2]

**Comment by tonyskansf** [comment]
**Adding item**
After creating a wishlist the user may add items he wishes to purchase in the future. That might be done in two ways: either via extension from another website, which requires further edit in the app (detailed information about an item) or through the app - information is filled in manually there. 

Both ways require categorization of the item. An item has an optional tag attribute. Each item may have dependency on another, which mean the item that is dependant on another can be purchases only when the other is already purchased.

Opravte pripadne okomentujte co byste zmenili
