### ISSUE TITLE
Model a "Maintaining a wishlist" use case

### ISSUE THREAD

**Issue by minndoo** [minndoo/varwish-modelling#9]

**Comment by tonyskansf** [comment]
Navrhuji zmenit nazev use case na _Maintaining a wishlist_ - do tady toho use case bych dal jak create a wishlist tak edit a wishlist.

### Maintaining a wishlist
This chapter describes the main functionality of the app. 
**UC1 - Creating a wishlist**
Allows a registered user to create an empty wishlist

**UC2 - Editing a wishlist**
Allows a registered user to edit his wishlist (name, items, category, etc.)

**Comment by tonyskansf** [comment]
Connect use case to corresponding requirement
